version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: unless-stopped      
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SynergyPCB
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped       
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: SynergyPCB
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: myadmin         
      ME_CONFIG_BASICAUTH_PASSWORD: StrongSynergyPCB!     
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

volumes:
  mongo-data:
