version: '3.8'

services:
  api:
    build: .
    container_name: pcb-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Fallbacks if not in .env
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"   # host:container